database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: nnunyula

  # the password
  password: Od2-gjgvOKXWf1_AAN0bRU5CMN0cbmPC

  # the JDBC URL
  url: jdbc:postgres://nnunyula:Od2-gjgvOKXWf1_AAN0bRU5CMN0cbmPC@echo.db.elephantsql.com:5432/nnunyula

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyApplication Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 2
  
  initialSize: 2

  # the maximum number of connections to keep open
  maxSize: 4

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false
  
server:
  applicationConnectors:
  - type: http 
    port: 8150
